routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Landing Page
//Route::get('/', function(){return view();});


//Auth
Route::get('/', 'Auth\AuthController@index')->name('login');
Route::post('/', 'Auth\AuthController@login')->name('logins');
Route::get('/redirect-nomor-surat/{q}', 'Auth\AuthController@postloginSSO');
Route::group(['middleware' => 'auth', 'ceklevel:Super Admin'], function(){

    // --- General ----
    Route::get('/dashboard', function(){
        return view('home');
    });
    Route::get('/home', 'DocsController@hitung_messages');
    Route::get('/logout', 'Auth\AuthController@logout')->name('logout');
    // Generate Nomor Surat
    Route::resource('depts', 'DeptsController');
    // Manage Document Type List
    Route::resource('docs', 'DocCodeController');
    // Manage Nomor Surat Generator
    Route::resource('surat', 'DocsController');
    // Manage Akun User
    Route::get('/user-account', 'UserAccountController@index');
    Route::get('/tambah-data', 'UserAccountController@tambah_data');
    Route::post('/tambah/proses', 'UserAccountController@proses_tambah');
    Route::patch('/update-proses/{id}', 'UserAccountController@proses_update');
    Route::patch('/update-proses-password/{id}', 'UserAccountController@proses_update_password');
    // Manage Dept User
    Route::get('/dept-user', 'DeptUserController@index');
    Route::get('/tambah-data-deptuser', 'DeptUserController@tambah_data_deptuser');
    Route::post('/tambah/proses-deptuser', 'DeptUserController@proses_tambah_deptuser');
    Route::patch('/update-proses-deptuser/{id}', 'DeptUserController@proses_update_deptuser');
    Route::get('/hapus-data-deptuser/{id}','DeptUserController@hapus_deptuser');
    // Manage Setting Akun
    Route::get('/setting-akun', 'SettingAkunController@index');
    Route::patch('/update-proses-akunpassword/{id}', 'SettingAkunController@proses_update_akunpassword');
    
    //  --- Sales Support --- 
    
    // Customer 
    
    // Quotation
    
    // --------------------------
    
    // Manage Department List 
});

Route::group(['middleware' => 'auth', 'ceklevel:Admin,User'], function(){

    // --- General ----
    Route::get('/dashboard', function(){
        return view('home');
    });
    Route::get('/home', 'DocsController@hitung_messages');
    Route::get('/logout', 'Auth\AuthController@logout')->name('logout');
    // Manage Nomor Surat Generator
    Route::resource('surat', 'DocsController');
     // Manage Setting Akun
     Route::get('/setting-akun', 'SettingAkunController@index');
    
    //  --- Sales Support --- 
    
    // Customer 
    
    // Quotation
    
    // --------------------------
    
    // Manage Department List 
});

app/Http/Controllers/UserAccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\User;
use Illuminate\Support\Facades\Auth;
use Validator;
use Hash;
use App\Department;
use Session;
use Illuminate\Support\Facades\DB;

class UserAccountController extends Controller
{
    //
    public function index()
    {
        $user = User::leftJoin('departments', 'departments.id', 'users.department_id')
        ->select(
            'users.*',
            'departments.name as department_name'
        )
        ->get();
        $department = DB::table('departments')->get();
        return view('user-account.index', compact('user', 'department'));
    }

    public function tambah_data()
    {
        $department = DB::table('departments')->get();
        return view('user-account.create', compact('department'));
    }

    public function proses_tambah(Request $request)
    {
        $this->validate(
            $request,
            [
                'email' => 'unique:users',
            ],
            [
                'email.unique' => 'Email sudah terdaftar, silahkan dicek kembali.',

            ]
        );        
        User::create([
                'name' => $request->name,
                'email' => $request->email,
                'level' => $request->level,
                'department_id' => $request->department_id,
                'password' => Hash::make($request->password),
                'email_verified_at' => $request->email_verified_at = Carbon::now(),
        ]);
        // dd($request->all());
        return redirect('/user-account')->with('success', 'Akun User Berhasil di Tambah');;
    }

    public function proses_update(Request $request, $id)
    {
     //    dd($request->all());
        DB::table('users')->where('id', $id)->update([
             'name' => $request->name,
             'email' => $request->email,
             'level' => $request->level,
             'department_id' => $request->department_id,
         ]);
         return redirect('/user-account')->with('success', 'Akun User Berhasil di Update');;
     }

     public function proses_update_password(Request $request, $id)
    {
     //    dd($request->all());
        DB::table('users')->where('id', $id)->update([
             'password' => Hash::make($request->password),
         ]);
         return redirect('/user-account')->with('success', 'Password Berhasil di Update');;
     }

}

resources/views/user-account/create.blade.php
@extends('layout.master')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="mx-auto">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Tambah Akun User</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Manajemen Akun User</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary">
                <form role="form" method="post" action="/tambah/proses" enctype="multipart/form-data">
                    @csrf

                    <div class="card-body">
                    @if(count($errors) > 0)
                        <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                            {{ $error }} <br/>
                            @endforeach
                        </div>
                        @endif
                    <div class="card-body">
                            <div class="form-group">
                                <label for="name">Nama</label>
                                <input type="text" class="form-control" name="name"
                                    placeholder="Input Nama" autocomplete="off" required>
                            </div>
                            
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" name="email"
                                    placeholder="Input Email" autocomplete="off" required>
                            </div>
                            
                            <div class="form-group">
                                <label for="level">Level</label>
                                <select name="level" class="form-control" required>
                                    <option value="">Pilih Level</option>
                                    <option value="Super Admin" {{ old('level') == "Super Admin" ? 'selected' : '' }}>Super Admin</option>
                                    <option value="Admin" {{ old('level') == "Admin" ? 'selected' : '' }}>Admin</option>
                                    <option value="User" {{ old('level') == "User" ? 'selected' : '' }}>User</option>
                                </select>
                            </div>

                            <!-- <div class="form-group">
                                <label for="department_id">Department</label>
                                <select class="form-control " name="department_id" required>
                                    <option value>Pilih Department</option>
                                    @foreach($department ?? '' as $department)
                                    <option value="{{ $department->id }}" {{ old('id') == "$department->id" ? 'selected' : '' }}>{{ $department->name }}</option>
                                @endforeach
                            </select> 
                            </div> -->

                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" name="password"
                                    placeholder="Input Password" autocomplete="off" id="myInput" required>
                                <br>
                                <!-- An element to toggle between password visibility -->
                                <input type="checkbox" onclick="myFunction()">Show Password
                            </div>
                    </div>
                    <div class="card-footer">
                        <input class="btn btn-primary float-right" type="submit" value="Submit">
                        <a class="btn btn-success" href="/tambah-data"><i class="fas fa-sync"></i> Clear Data</a>
                    </div>
            </div>
    </section>


</div>
@endsection

<script>
function myFunction() {
  var x = document.getElementById("myInput");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}
</script>

resources/views/user-account/index.blade.php
@extends('layout.master')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="mx-auto">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Manajemen Akun User</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Akun User</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>



    <section class="content">
        <div class="container-fluid">
            <div class="row mb-2 ">
                <div class="col-sm-6">
                    <a href="/tambah-data" type="button" class="btn btn-secondary">
                        <i class="fas fa-plus-square"></i>
                        Add User Account
                    </a>
                </div>
            </div>
            <br>
                <div class="card card-primary">
                    <div class="card-body">
                        <table class="table table-bordered table-striped example4">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Level</th>
                                    <!-- <th>Department</th> -->
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($user as $d)
                                <tr>
                                    <td>{{$d->id}}</td>
                                    <td>{{$d->name}}</td>
                                    <td>{{$d->email}}</td>
                                    <td>{{$d->level}}</td>
                                    <!-- <td>{{$d->department_name}}</td> -->
                                    <td>
                                        <a class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal-editbio-{{ $d->id }}"
                                            data-doc_type="" data-req_date>
                                            <span class="fas fa-pencil-alt"></span>
                                        </a>
                                        <!-- <a class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#modal-editpassword-{{ $d->id }}"
                                            data-doc_type="" data-req_date>
                                            <span class="fas fa-lock"></span>
                                        </a>     -->
                                        <a class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-detail-{{ $d->id }}"
                                            data-doc_type="" data-req_date>
                                            <span class="fas fa-info"></span>
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
        </div>
    </section>
    <br>

    @foreach($user as $data)
    <div class="modal fade" id="modal-editbio-{{ $data->id }}">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3> Edit Data </h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body table-responsive">
                    <form action="{{url('update-proses/'.$data->id)}}" enctype="multipart/form-data" method="POST">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label for="name">Nama</label>
                        <input type="text" class="form-control" name="name" placeholder="Masukkan Nama" value="{{ $data->name }}">
                    </div>

                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" name="email" placeholder="Masukkan Email" value="{{ $data->email }}">
                    </div>

                    <div class="form-group">
                        <label for="level">Level</label>
                        <select name="level" class="form-control">
                            <option value="" disabled>Pilih Level</option>
                            <option value="{{ $data->level }}">{{ $data->level }} </option>
                            <option value="Super Admin">Super Admin</option>
                            <option value="Admin">Admin</option>
                            <option value="User">User</option>
                        </select>
                    </div>
                    

                    <!-- <div class="form-group">
                        <label for="level">Department</label>
                        <select name="department_id" class="form-control">
                            <option value="" disabled>Pilih Department</option>
                            <option value="{{ $data->department_id }}">{{ $data->department_name }}</option>
                            
                            @foreach($department ?? '' as $deps)
                            <option value="{{ $deps->id }}">{{ $deps->name }}</option>
                            @endforeach
                        </select>
                    </div> -->
                    
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary float-right">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endforeach

@foreach($user as $data)
    <div class="modal fade" id="modal-editpassword-{{ $data->id }}">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3> Update Password </h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{url('update-proses-password/'.$data->id)}}" enctype="multipart/form-data" method="POST">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" name="email" placeholder="Masukkan Email" value="{{ $data->email }}" readonly>
                    </div>

                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="text" class="form-control" name="password"
                        placeholder="Input Password" autocomplete="off" required>    
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary float-right">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endforeach

        @foreach($user as $data)
    <div class="modal fade" id="modal-detail-{{ $data->id }}">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3> Detail Data </h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body table-responsive">
                    <!-- <form action="{{route('surat.show', 'id')}}" method="get"> -->
                        <table class="table table-bordered no-margin">
                            <tbody>
                                <tr>
                                    <th>Nama</th>
                                    <td>{{$data->name}}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{$data->email}}</td>
                                </tr>
                                <tr>
                                    <th>Level</th>
                                    <td>{{$data->level}}</td>
                                </tr>
                                <!-- <tr>
                                    <th>Department</th>
                                    <td>{{$data->department_name}}</td>
                                </tr> -->
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endforeach


@endsection